#!/bin/bash
# Auto-generated by claude-governance
# Secret detection hook

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name')

# Only check Write/Edit operations
if [[ "$TOOL_NAME" != "Write" && "$TOOL_NAME" != "Edit" ]]; then
  exit 0
fi

CONTENT=$(echo "$INPUT" | jq -r '.tool_input.content // .tool_input.new_string')

# Check for: AWS Access Key
if echo "$CONTENT" | grep -qE 'AKIA[0-9A-Z]{16}'; then
  echo "AWS Access Key detected. Secret detected. Use environment variables instead." >&2
  exit 2
fi

# Check for: GitHub PAT
if echo "$CONTENT" | grep -qE 'ghp_[a-zA-Z0-9]{36}'; then
  echo "GitHub PAT detected. Secret detected. Use environment variables instead." >&2
  exit 2
fi

# Check for: API Key
if echo "$CONTENT" | grep -qE 'sk-[a-zA-Z0-9_-]{48,}'; then
  echo "API Key detected. Secret detected. Use environment variables instead." >&2
  exit 2
fi

exit 0
